version: '3.8' 

services:
  web:
    build: .  
    volumes:
      - mfa:/app  
    environment:
      - PYTHONPATH=/app  
      - SECRET_KEY=${SECRET_KEY}
      - DB_USER=${DB_USER}  
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - TWILIO_ACCOUNT_SID=${TWILIO_ACCOUNT_SID}
      - TWILIO_AUTH_TOKEN=${TWILIO_AUTH_TOKEN}
      - TWILIO_SERVICE_SID=${TWILIO_SERVICE_SID}
      - TWILIO_PHONE=${TWILIO_PHONE}
    ports:
      - "5001:5000"
    depends_on:
      - db
    networks:
      - mfa_network

  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=mfa_demo
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - mfa_network
      
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080" 
    depends_on:
      - db 
    networks:
      - mfa_network

volumes:
  db_data: 
  mfa:

networks:
  mfa_network: